/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "background": "#fafaf5",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f1f1ec",
        "inverse-primary": "#88d982",
        "inverse-surface": "#2f312e",
        "on-background": "#1a1c19",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-primary-container": "#cbffc2",
        "on-primary-fixed": "#002204",
        "on-primary-fixed-variant": "#005312",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#694300",
        "on-secondary-fixed": "#2a1800",
        "on-secondary-fixed-variant": "#643f00",
        "on-surface": "#1a1c19",
        "on-surface-variant": "#40493d",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffeee8",
        "on-tertiary-fixed": "#380d00",
        "on-tertiary-fixed-variant": "#802a00",
        "outline": "#707a6c",
        "outline-variant": "#bfcaba",
        "primary": "#0d631b",
        "primary-container": "#2e7d32",
        "primary-fixed": "#a3f69c",
        "primary-fixed-dim": "#88d982",
        "secondary": "#835400",
        "secondary-container": "#fcab28",
        "secondary-fixed": "#ffddb5",
        "secondary-fixed-dim": "#ffb957",
        "surface": "#fafaf5",
        "surface-bright": "#fafaf5",
        "surface-container": "#eeeee9",
        "surface-container-high": "#e8e8e3",
        "surface-container-highest": "#e3e3de",
        "surface-container-low": "#f4f4ef",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dadad5",
        "surface-tint": "#1b6d24",
        "surface-variant": "#e3e3de",
        "tertiary": "#993300",
        "tertiary-container": "#c24300",
        "tertiary-fixed": "#ffdbcf",
        "tertiary-fixed-dim": "#ffb59a"
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
